server:
  port: 9003

spring:
  application:
    name: REPLY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/tweetdb
    username: root
    password: Ashes1In1The4Snow6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true